### ISSUE TITLE
Faire le calendrier des journées nationales et internationales en lien avec beta

### ISSUE THREAD

**Issue by marinepurson2** [betagouv/animation-communaute#119]

**Comment by marinepurson2** [comment]
@dtende peux-tu me dire où tu as mis le calendrier ? 
Est-ce que tu pourras le mettre sur cette page stp : https://www.notion.so/betagouv-dinum/Journ-es-nationales-et-internationales-11f59e111b8b806a8e35fa7c3ec1f3ae

**Comment by dtende** [comment]
@dtende c'est actualisé je l'ai mis dans le pad benchmark
