### ISSUE TITLE
Tester le sondage sur quelques utilisateur.ices

### ISSUE THREAD

**Issue by fannyblanc** [betagouv/animation-communaute#458]
Sondage envoyé à l'équipe communauté. 
Sondage : https://tally.so/r/mBQ0Be

**Comment by fannyblanc** [comment]
Retours : 

- [x] - Mettre des mots en gras dans le texte d'intro 
- [x] - Aérer le texte d'intro
- [x] - Mettre sur deux pages 
- [x] - "celles et ceux qui l'ont testé on mis 1min30, peux-tu faire mieux ? "
- [x] - zone de commentaires libres 
- [x] - améliorer message groupe de soutien
- [x] - rétablir le lien logique groupe de soutien
- [x] - grille pour la question sur l'utilité des dispositifs
- [x] Rephrase "qu'est-ce qui est le plus difficile pour toi / qu'est-ce qui te demande le plus d'efforts"
- [x] Champ de réponses ouvert après "as tu le sentiment de faire partie de la communauté"

**Comment by astranchet** [comment]
@fannyblanc 

- j'ai fait une proposition de grille, mais je n'ai pas encore supprimé les anciennes questions et publié ("Publish").
- Pour l'idée de mettre sur 2 pages, on couperait où ? Avant les questions "à propos de toi" ?

**Comment by fannyblanc** [comment]
@astranchet 
Oui on couperait sur à propos de toi. Tu penses que c'est une bonne idée ?

**Comment by astranchet** [comment]
Oui, ça peut être bien. Ça donne visuellement l'impression que le formulaire est moins long ; et par ailleurs, les 3 dernieres questions sont un peu des "no brainer" (sauf celle du champ libre, mais c'est toujours le dernier truc attendu).

Par contre, maintenant que la matrice "À quel point ces dispositifs te sont utiles ?" est en ligne, je serai catégorique et je supprimerais la question "Qu'est-ce qui a le plus de valeur pour toi parmi ces dispositifs proposés par la communauté beta.gouv.fr ? ", voir même "Qu'est-ce qui est le plus facile d'accès pour toi / Qu'est-ce qui te demande le moins d'effort ?"

**Comment by marinepurson2** [comment]
Pour ma part, je ne comprends pas bien l'utilité de la matrice. Si les gens disent que les formations ne leur sont jamais utiles, alors on les supprime ? 

Je trouve que l'idée du classement par valeur et facilité d'accès m'aiguille plus pour savoir où mettre mon énergie au quotidien.

Et je remets ici mes retours de Mattermost : 
- dans "As-tu le sentiment de faire partie de la communauté beta.gouv.fr ?", est-ce qu'il y aurait pas un champ de réponse ouvert pour voir ce que les gens proposent en spontanée sur pourquoi ils se sentent appartenir ou pas ?
- sur la question "Qu'est-ce qui a le plus de valeur pour toi parmi ces dispositifs proposés par la communauté beta.gouv.fr ?" je me retrouve à déclasser le forum alors que ce que j'y apprécie c'est le partage d'expérience (en fait on a des natures de réponses différentes j'ai l'impression)
