### ISSUE TITLE
Benchmark contenu

### ISSUE THREAD

**Issue by dtende** [betagouv/animation-communaute#476]

**Comment by marinepurson2** [comment]
@dtende tu l'as mis où ?

**Comment by dtende** [comment]
ici @marinepurson2 : https://www.notion.so/betagouv-dinum/Le-compte-LinkedIn-beta-gouv-fr-10aaef709d1b411380cc717b9c13a4bf

**Comment by marinepurson2** [comment]
Lien vers le PAD/slides : https://pad.numerique.gouv.fr/FMhHTiLlTtuG1VFxq5syjg

**Comment by dtende** [comment]
@marinepurson2 le lien : https://pad.numerique.gouv.fr/FMhHTiLlTtuG1VFxq5syjg?both
Petit souci : je ne peux intégrer visiblement des images, le format est trop grand et je ne sais pas comment réduire
