### ISSUE TITLE
Suivre les stats du sondage

### ISSUE THREAD

**Issue by marinepurson2** [betagouv/animation-communaute#488]

**Comment by marinepurson2** [comment]
Stats de participation suivies sur Notion : https://www.notion.so/betagouv-dinum/Communication-sondage-56be8fea3e3543faaf78c199bc3742e2

**Comment by dtende** [comment]
@marinepurson2 je n'ai pas accès à la partie réponse au sondage bien-être,  est-ce que c'est uniquement toi qui t'en occupe ? Ou alors je suis uniquement celles sur Brevo ?
