### ISSUE TITLE
Rédiger un post LinkedIn pour valoriser le forum + la création de la Ruche numérique

### ISSUE THREAD

**Issue by marinepurson2** [betagouv/animation-communaute#500]
```[tasklist]
### Rétroplanning
- [x] Rédiger le post le 04/11
- [ ] Faire valider à Marine le 05/11
- [ ] Faire valider à Jenn et Fanny le 06/11
- [ ] Faire une photo du forum le 7/11 pour illustrer le post
- [ ] Publier le post le jeudi 7/11
```

**Comment by marinepurson2** [comment]
Le forum du 7/11 sera l'occasion de valoriser l'incubateur du ministère de l'Agriculture, de la Souveraineté alimentaire et de la Forêt : la Ruche numérique, qui s'est créé en septembre 2024.

Pour cela, je te propose qu'on prévoit un post LinkedIn à publier le jeudi 7 novembre. On peut partir du contexte, le forum, pour annoncer la création de l'incubateur.

Dans ce post, on peut donc : 
- mettre en avant un ou deux éléments de la journée forum (a priori il y aura les ministres Guillaume Kasbarian et Annie Genevard)
- présenter l'incubateur et ses missions

Pour cela, tu peux t'appuyer sur un précédent post qu'on avait fait pour annoncer la [création de l'incubateur du Cerema](https://www.linkedin.com/feed/update/urn:li:activity:7206905687870717952), sur le [programme de la journée](https://grist.numerique.gouv.fr/o/docs/dz6U4msbsub4/Forum-betagouvfr-Touteslessalles?utm_id=share-doc) et sur la [présentation de la Ruche numérique](https://beta.gouv.fr/incubateurs/agriculture.html).

**Comment by dtende** [comment]
@marinepurson2 

Bonjour Marine, voici mon post rédigé : 

**Quand beta.gouv.fr et le Ministère de l'Agriculture et de la Souveraineté alimentaire et de la Forêt  se réunissent pour inaugurer le lancement du nouvel incubateur : la “Ruche du Numérique”** 

Depuis cet été maintenant, le **Ministère de l'Agriculture et de la Souveraineté alimentaire et de la Forêt** (MASAF) a lancé son incubateur **“La Ruche du Numérique”** pour continuer d’encourager l'accompagnement et la floraison des initiatives numériques autour de la transition agricole et alimentaire au service de tous les usagers

Et si pour beta.gouv.fr cela représente le succès de l'implantation d' incubateurs dédiés aux politiques publiques. Il n’en reste pas moins le succès également du Ministère qui continue de porter ses ambitions et de les promouvoir auprès du grand public grâce à l’aide du numérique. 

Un double succès que nous souhaitions co-célébrer lors de la tenue **le jeudi 7 novembre de notre forum** ouvert à l’ensemble des membres de la communauté dans l'optique de découvrir, partager autour des **startups d'État du MASAF** mais aussi de nos startups d'Etat. 

Pour cette édition assez spéciale nous serons en compagnie de la Ministre de l'Agriculture, de la Souveraineté alimentaire et de la Forêt **Annie Genevard** et du Ministre délégué auprès du ministre de la Transition écologique et de la Cohésion des territoires chargé du logement **Guillaume Kasbarian**.

A toute la communauté beta.gouv.fr rendez-vous **le 7 novembre** !

#inauguration #forum #beta.gouv #Ministre de l'Agriculture, de la Souveraineté alimentaire et de la Forêt

**Comment by dtende** [comment]
@marinepurson2 : Je ne sais s'il fallait un call to action à la fin du post, je l'ai tout de même inséré au cas où

**Comment by marinepurson2** [comment]
Alors, sur le fond, tous les éléments sont bons.

On pourrait accentuer les missions de la Ruche numérique, ils ont mis les éléments suivants dans leur note ministre (à synthétiser évidemment) : 
- La Ruche numérique du MASAF a pour objectif de diffuser au sein du ministère les méthodes dites « produit » et centrées sur la réponse aux besoins des utilisateurs.
- À cette fin, elle développe :
•	une activité d’incubation, au sens de l’approche Startup d'État ; les directions porteuses d’une «Startup d’État » (DGAL, DGPE, Agence Bio...) incubée par La Ruche ont adhéré d’emblée aux trois piliers de la méthode « beta.gouv.fr » ;
•	une offre d’accompagnement consistant à mettre des compétences (produit et design) à disposition de projets et produits nés au sein du Service numérique mais en dehors de l’incubateur. 


Sur la forme, il faut plus être un peu plus incisif et plus proche de notre tonalité habituelle.

1. Accroche : il faut que ça fasse écho à la photo du forum qu'on postera + qu'on rentre dans le vif du sujet : le lancement
2. Contexte et lien avec beta : ça se passe au forum de la communauté beta.gouv.fr
3. Sujet principal : Présentation de la Ruche + ses missions
4. Recentrer sur beta.gouv.fr : le réseau des incubateurs s'agrandit (+ chiffre clé) + ça renforce le soutien des agents publics pour les aider à résoudre les problèmes de terrain au service des citoyens, des agents publics, des collectivités... 
5. Call to action : allez découvrir le réseau des incubateurs sur beta.gouv.fr

(On va poster pendant ou après l'événement, donc le CTA ne peut pas être RDV le 7 novembre, ça aurait fonctionné si on postait aujourd'hui)

**Comment by dtende** [comment]
@marinepurson2 

Voici les modifications apportées

[Ce jeudi ou aujourd’hui] au forum mensuel, on **célèbre le lancement de l'incubateur du Ministère de l'Agriculture et de la Souveraineté alimentaire et de la Forêt** : “**La Ruche du Numérique !**

Si c’est bel et bien depuis cet été que l’incubateur a vu le jour avec comme mission de **diffuser au sein du ministère les méthodes dites « produit » et des services utiles aux utilisateurs**, en développant notamment auprès des directions porteuses l’approche **Startup d'État, la méthode beta.gouv.fr et une offre d’accompagnement** pour mettre à disposition des compétences auprès des projets / produits pérennisés, nés initialement en son sein. 

La Ruche Numérique a également décidé de se joindre à l’organisation du forum mensuel pour fêter avec l’ensemble de la communauté beta.gouv.fr le lancement du **22ème incubateur** au sein de la famille autour d’un programme pour découvrir ses quelques startups d'État parmi les **11 existantes** ( Carto Bio, Ma Cantine, Maestro…) mais aussi parler **numérique** ! 

Un moment unique partagé aux côtés d’@**Annie Genevard,** Ministre de l'Agriculture, de la Souveraineté alimentaire et de la Forêt et de @**Guillaume Kasbarian**, Ministre chargé du logement.

C’est une nouvelle page dans notre **histoire et celle de notre réseau !** 

**Pour en savoir plus sur notre réseau beta.gouv.fr** - [Réseau d'incubateurs — beta.gouv.fr](https://beta.gouv.fr/incubateurs/)

#inauguration #forum #beta.gouv #Ministre de l'Agriculture, de la Souveraineté alimentaire et de la Forêt

**Comment by dtende** [comment]
@marinepurson2, il y a également cette présentation qui est possible ( juste une légère modification au niveau de la présentation des activités réalisés. 

[Ce jeudi ou aujourd’hui] au forum mensuel, on célèbre le **lancement de l'incubateur du Ministère de l'Agriculture et de la Souveraineté alimentaire et de la Forêt** : “**La Ruche du Numérique !**

Si c’est bel et bien depuis cet été que l’incubateur a vu le jour avec comme mission de **diffuser au sein du ministère les méthodes dites « produit » et des services utiles aux utilisateurs**, en développant notamment : 

1. auprès des directions porteuses l’approche **Startup d'État, la méthode beta.gouv.fr 
2.  une offre d’accompagnement** pour mettre à disposition des compétences auprès des projets / produits pérennisés, nés initialement en son sein. 

La Ruche Numérique a également décidé de se joindre à l’organisation du forum mensuel pour fêter avec l’ensemble de la communauté beta.gouv.fr le lancement du **22ème incubateur** au sein de la famille autour d’un programme pour découvrir ses quelques startups d'État parmi les **11 existantes** ( Carto Bio, Ma Cantine, Maestro…) mais aussi parler **numérique** ! 

Un moment unique partagé aux côtés d’@**Annie Genevard,** Ministre de l'Agriculture, de la Souveraineté alimentaire et de la Forêt et de @**Guillaume Kasbarian**, Ministre chargé du logement.

C’est une nouvelle page dans notre **histoire et celle de notre réseau !** 

**Pour en savoir sur notre réseau beta.gouv.fr** - [Réseau d'incubateurs — beta.gouv.fr](https://beta.gouv.fr/incubateurs/)

#inauguration #forum #beta.gouv #Ministre de l'Agriculture, de la Souveraineté alimentaire et de la Forêt
