### ISSUE TITLE
relance fiches membres incomplètes

### ISSUE THREAD

**Issue by revolunet** [betagouv/animation-communaute#523]
# relance espace membre

## Objectif

Compléter fiches membres vides. 

## Methode

 - cibles:
    - utilisateurs n'ayant pas modifié leur fiche depuis + 3 mois
    - avec une date de fin dans le futur
    - sans SE et sans team
    - -> [101 users](https://metabase.incubateur.net/question/135-membres-actifs-sans-mise-a-jour-recente-sans-se)

## Message

Hello !

Est-ce que tu aurais 2 minutes pour compléter [ta fiche membre beta.gouv.fr](https://espace-membre.incubateur.net/account/base-info) ?

Ce serait super si tu pouvais indiquer les produits sur lesquels tu oeuvres ou a oeuvré et/ou tes compétences. Cela nous permettrait d'enrichir les données de la communauté et de mieux se connaître !

Un grand merci de la part de l'équipe communauté qui reste à ta disposition;

## Todo

 - [ ] valider le message
 - [ ] automatiser dans espace-membre ? quid suivi

**Comment by astranchet** [comment]
Proposition (vaguement plus) **👮 Bad Cop 👮** à envoyer à celles et ceux qui n'ont pas remplis de mission (ça me paraît le plus grave) : 

> Hello !
>
> Pourrais-tu compléter [ta fiche membre beta.gouv.fr](https://espace-membre.incubateur.net/account/base-info)  ? Actuellement, nous n'avons pas d'information sur les produits ou l'incubateur pour lequel tu travailles. 
>
> Au passage, n'hésite pas aussi à indiquer tes compétences, pour nous permettre de mieux connaître la communauté 🙏

**Comment by revolunet** [comment]
tout est prêt sur brevo pour un 1er envoi ([94 membres](https://metabase.incubateur.net/question/135-membres-actifs-sans-mise-a-jour-recente-sans-se))

on pourra automatiser ensuite

**Comment by astranchet** [comment]
Ça marche bien, je l'ai reçu mais je ne peux pas renseigner une équipe transverse 🙈

**Comment by revolunet** [comment]
pour l'instant on est passé de 80 a 45 fiches incomplètes
