### ISSUE TITLE
Identifier 2 produits pour #lundiproduit

### ISSUE THREAD

**Issue by dtende** [betagouv/animation-communaute#528]

**Comment by dtende** [comment]
@marinepurson2 

**Idées de produits à aborder pour le mois de décembre** 

- **Ma Cantine** - angle d’approche :  restauration collective, transparence sur les aliments dans l'assiette *[incubateur : La Ruche numérique - l'Incubateur du Ministère de l'Agriculture, de la Souveraineté alimentaire et de la forêt)*

- **Transport.data.gouv.fr ** - angle d’approche : *les déplacements de fin d’année [ incubateur La Fabrique Numérique de l'Ecologie (MTE-MCT)]*

ou 

- **Nos gestes climats** - angle d’approche : calculer et réduire son empreinte Carbonne à l’approche des fêtes [incubateur :  l'Accélérateur de la transition écologique (ADEME) ]

**Comment by marinepurson2** [comment]
@dtende ok pour Ma Cantine et Nos Gestes Climat !

Pour décembre ou début janvier on peut aussi prévoir Signal Conso : https://beta.gouv.fr/startups/signalement.html (avec l'angle défense des droits de consommateurs)
