### ISSUE TITLE
Rédiger le post lancement #lundiproduit 

### ISSUE THREAD

**Issue by dtende** [betagouv/animation-communaute#529]

**Comment by dtende** [comment]
@marinepurson2 

Pour correction : 

**Nouveau  :  On découvre un produit chaque lundi  !**

Si on avait l’habitude de vous parlez  de nos produits, de leur impact et de leurs usages, à quelques semaines  de la nouvelle année , on s’est penché sur une nouvelle problématique comment alimenter nos interactions avec vous et votre intérêt à découvrir l’environnement beta.gouv.fr ? 

La réponse, on a fini par la trouver et la formaliser par la création d’un nouveau concept le **#Lundiproduit** 

**Mais qu’est-ce que c’est ?** 

C’est une rubrique animée chaque lundi conçue pour découvrir ou s’informer mais aussi partager et échanger autour des produits de la communauté. 

**La discussion est ouverte !**

Vous l’aurez compris ce concept ne peut pas exister sans vous !

Alors que vous soyez celui qui est : 

- Curieux d’en apprendre plus sur un produit,
- Désireux de faire connaître un produit,
- Ou simplement intéressé par les initiatives de la communauté Beta autour d’un sujet précis,

Il ne vous reste plus qu’une seule chose à faire, vous rendre dans l’espace commentaire et nous soumettre votre proposition. 

Pensez également à partager ce post pour nous permettre de collecter un maximum d’avis et vous proposez les contenus les plus intéressants possibles !

**Comment by marinepurson2** [comment]
@dtende merci ! J'ai simplifié et raccourci, vu que c'est pas un post avec du contenu, autant être le plus efficace possible. Je te laisse le poster lundi matin ?

🔔 Chaque lundi, un produit !

beta.gouv.fr, c'est plus de 280 services publics numériques créés depuis 2015. Vous les connaissez ? Et savez-vous lesquels pourraient vous être utiles ?

Pour vous permettre de découvrir les produits conçus par les équipes du réseau beta.gouv.fr, on vous propose chaque lundi un focus sur l'un de nos services ! 🔎

Et pour ça, on a besoin de vous : 
- Envie d’en apprendre plus sur un produit ?
- Intéressé par les services autour d'une thématique ou d'un sujet ?
- Ou besoin de faire connaître votre produit si vous travaillez dans le réseau beta.gouv.fr ?

Une seule chose à faire : dites nous en commentaire quel(s) service(s) vous voulez découvrir ! 👇

Pour en savoir plus sur les services publics numériques conçus dans le réseau beta.gouv.fr, c'est par ici : beta.gouv.fr
